### ISSUE TITLE
confirmed working environment

### ISSUE THREAD

**Issue by chaseadam** [Spearfoot/disk-burnin-and-testing#15]
Thanks for the tool! If you cared to include in the readme:

fedora 33 workstation
WDC_WD140EDFZ-11A0VA0 (RED?)

[burnin-WDC_WD140EDFZ-11A0VA0_Y5HVU25C.log](https://github.com/Spearfoot/disk-burnin-and-testing/files/5958827/burnin-WDC_WD140EDFZ-11A0VA0_Y5HVU25C.log)

**Comment by Spearfoot** [comment]
Added to readme -- thanks!
