### ISSUE TITLE
Question: Utilisation of -c?

### ISSUE THREAD

**Issue by JoshStark** [Spearfoot/disk-burnin-and-testing#18]
Hi, I came across this script and it's incredibly helpful, so thanks! One question I have is why you opted to change the blocksize flag to `-b 8192` rather than, say, double the blocks written using `-c`? 

I found running `badblocks` with the option `-b 4096` was writing at around 25M/s which would have resulted in my 8T drive completing after 16 days. By modifying the call to badblocks to use `-b 4096 -c 128` (double the default), I did see an almost double increase in write speeds. I didn't fancy going higher just to avoid any potential issues with badblocks misreporting anything, but figured there must be a sweet spot somewhere for larger drives?

Thanks.

**Comment by Spearfoot** [comment]
Thanks! 

We doubled the block size to accommodate larger drives.

Your suggestion to increase the number of blocks is a good one. I've tinkered with it in the past, but... it takes a long time to thoroughly test all combinations and permutations of options, and I don't have unlimited time to experiment... So it fell by the wayside.

Also, I've always assumed anyone with enough interest to find this script would also be the kind of person who would tinker with it, too, just as I do.

Please let me know if your experience shows that increasing the blocks makes a significant difference in runtime.
