### ISSUE TITLE
Inappropriate ioctl

### ISSUE THREAD

**Issue by CoreyVidal** [Spearfoot/disk-burnin-and-testing#5]
Hi. I'm new to FreeNAS and setting up my first NAS. Been slowly working my way through figuring everything out.

I'm running your script as we speak on 1 drive of mine. It just returned this:

```shell
+-----------------------------------------------------------------------------
+ Run badblocks test on drive /dev/da0: Sat Jun 20 15:46:58 EDT 2020
+-----------------------------------------------------------------------------
Checking for bad blocks in read-write mode
From block 0 to 1465130645
Testing with pattern 0xaa: set_o_direct: Inappropriate ioctl for device
`  6.86% done, 31:09 elapsed. (0/0/0 errors)
```

I'm not sure what `inappropriate ioctl` is, and this thing still has 9+ hours to go before it's done. Should I be concerned?

If it helps, the disk I'm running it on is a Seagate Enterprise NAS drive. 6 TB. SATA 3.0 (6 Gbps). Model number is ST6000NM0115-1YZ.

I don't think or expect you to help me with my particular device. Just wondering if you might share some insight?

Thanks!

**Comment by Spearfoot** [comment]
Hi!

Nothing to worry about -- it always displays that message on FreeBSD/FreeNAS, but always runs successfully.

**Comment by CoreyVidal** [comment]
Thank you, that's great! Might I recommend mentioning that in the documentation somewhere?

**Comment by Spearfoot** [comment]
That's a good idea. Thanks
