### ISSUE TITLE
New version mistakenly identifies WDC Green disk as 'non mechanical' 

### ISSUE THREAD

**Issue by Spearfoot** [Spearfoot/disk-burnin-and-testing#9]
And as a result, skips execution of badblocks program.

WDC Green model: WDC_WD20EARX-00PASB0

**Comment by rakoczy** [comment]
The same for WDC_WD800AAJS

**Comment by Spearfoot** [comment]
Committed new version that fixes this problem. Unless a disk returns a Rotation Rate of "Solid State Disk", we will treat it as a mechanical drive.
